// Code generated by MockGen. DO NOT EDIT.
// Source: filter.sql.go
//
// Generated by this command:
//
//	mockgen -source=filter.sql.go -destination=mock/filter.sql.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dbpostgres "example/dbpostgres"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFilterQuerier is a mock of FilterQuerier interface.
type MockFilterQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockFilterQuerierMockRecorder
	isgomock struct{}
}

// MockFilterQuerierMockRecorder is the mock recorder for MockFilterQuerier.
type MockFilterQuerierMockRecorder struct {
	mock *MockFilterQuerier
}

// NewMockFilterQuerier creates a new mock instance.
func NewMockFilterQuerier(ctrl *gomock.Controller) *MockFilterQuerier {
	mock := &MockFilterQuerier{ctrl: ctrl}
	mock.recorder = &MockFilterQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterQuerier) EXPECT() *MockFilterQuerierMockRecorder {
	return m.recorder
}

// ListFilterItems mocks base method.
func (m *MockFilterQuerier) ListFilterItems(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.ListFilterItemsParams) ([]dbpostgres.ListFilterItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilterItems", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.ListFilterItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilterItems indicates an expected call of ListFilterItems.
func (mr *MockFilterQuerierMockRecorder) ListFilterItems(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilterItems", reflect.TypeOf((*MockFilterQuerier)(nil).ListFilterItems), ctx, db, arg)
}

// SearchFilterItems mocks base method.
func (m *MockFilterQuerier) SearchFilterItems(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchFilterItemsParams) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFilterItems", ctx, db, arg)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFilterItems indicates an expected call of SearchFilterItems.
func (mr *MockFilterQuerierMockRecorder) SearchFilterItems(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFilterItems", reflect.TypeOf((*MockFilterQuerier)(nil).SearchFilterItems), ctx, db, arg)
}
