// Code generated by MockGen. DO NOT EDIT.
// Source: lock.sql.go
//
// Generated by this command:
//
//	mockgen -source=lock.sql.go -destination=mock/lock.sql.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dbpostgres "example/dbpostgres"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLockQuerier is a mock of LockQuerier interface.
type MockLockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockLockQuerierMockRecorder
	isgomock struct{}
}

// MockLockQuerierMockRecorder is the mock recorder for MockLockQuerier.
type MockLockQuerierMockRecorder struct {
	mock *MockLockQuerier
}

// NewMockLockQuerier creates a new mock instance.
func NewMockLockQuerier(ctrl *gomock.Controller) *MockLockQuerier {
	mock := &MockLockQuerier{ctrl: ctrl}
	mock.recorder = &MockLockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockQuerier) EXPECT() *MockLockQuerierMockRecorder {
	return m.recorder
}

// GetUserWithLock mocks base method.
func (m *MockLockQuerier) GetUserWithLock(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.GetUserWithLockParams) (*dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithLock", ctx, db, arg)
	ret0, _ := ret[0].(*dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithLock indicates an expected call of GetUserWithLock.
func (mr *MockLockQuerierMockRecorder) GetUserWithLock(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithLock", reflect.TypeOf((*MockLockQuerier)(nil).GetUserWithLock), ctx, db, arg)
}
