// Code generated by MockGen. DO NOT EDIT.
// Source: search.sql.go
//
// Generated by this command:
//
//	mockgen -source=search.sql.go -destination=mock/search.sql.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dbpostgres "example/dbpostgres"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchQuerier is a mock of SearchQuerier interface.
type MockSearchQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockSearchQuerierMockRecorder
	isgomock struct{}
}

// MockSearchQuerierMockRecorder is the mock recorder for MockSearchQuerier.
type MockSearchQuerierMockRecorder struct {
	mock *MockSearchQuerier
}

// NewMockSearchQuerier creates a new mock instance.
func NewMockSearchQuerier(ctrl *gomock.Controller) *MockSearchQuerier {
	mock := &MockSearchQuerier{ctrl: ctrl}
	mock.recorder = &MockSearchQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchQuerier) EXPECT() *MockSearchQuerierMockRecorder {
	return m.recorder
}

// SearchUsers mocks base method.
func (m *MockSearchQuerier) SearchUsers(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchUsersParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockSearchQuerierMockRecorder) SearchUsers(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsers), ctx, db, arg)
}

// SearchUsersByContact mocks base method.
func (m *MockSearchQuerier) SearchUsersByContact(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchUsersByContactParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersByContact", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByContact indicates an expected call of SearchUsersByContact.
func (mr *MockSearchQuerierMockRecorder) SearchUsersByContact(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByContact", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsersByContact), ctx, db, arg)
}

// SearchUsersByIDs mocks base method.
func (m *MockSearchQuerier) SearchUsersByIDs(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchUsersByIDsParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersByIDs", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByIDs indicates an expected call of SearchUsersByIDs.
func (mr *MockSearchQuerierMockRecorder) SearchUsersByIDs(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByIDs", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsersByIDs), ctx, db, arg)
}

// SearchUsersOrdered mocks base method.
func (m *MockSearchQuerier) SearchUsersOrdered(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchUsersOrderedParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersOrdered", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersOrdered indicates an expected call of SearchUsersOrdered.
func (mr *MockSearchQuerierMockRecorder) SearchUsersOrdered(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersOrdered", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsersOrdered), ctx, db, arg)
}

// SearchUsersOrderedByID mocks base method.
func (m *MockSearchQuerier) SearchUsersOrderedByID(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchUsersOrderedByIDParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersOrderedByID", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersOrderedByID indicates an expected call of SearchUsersOrderedByID.
func (mr *MockSearchQuerierMockRecorder) SearchUsersOrderedByID(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersOrderedByID", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsersOrderedByID), ctx, db, arg)
}

// SearchUsersWithBlock mocks base method.
func (m *MockSearchQuerier) SearchUsersWithBlock(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchUsersWithBlockParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersWithBlock", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersWithBlock indicates an expected call of SearchUsersWithBlock.
func (mr *MockSearchQuerierMockRecorder) SearchUsersWithBlock(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersWithBlock", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsersWithBlock), ctx, db, arg)
}

// SearchUsersWithSameNameAndEmail mocks base method.
func (m *MockSearchQuerier) SearchUsersWithSameNameAndEmail(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchUsersWithSameNameAndEmailParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersWithSameNameAndEmail", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersWithSameNameAndEmail indicates an expected call of SearchUsersWithSameNameAndEmail.
func (mr *MockSearchQuerierMockRecorder) SearchUsersWithSameNameAndEmail(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersWithSameNameAndEmail", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsersWithSameNameAndEmail), ctx, db, arg)
}

// SearchUsersWithTopStyle mocks base method.
func (m *MockSearchQuerier) SearchUsersWithTopStyle(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.SearchUsersWithTopStyleParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersWithTopStyle", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersWithTopStyle indicates an expected call of SearchUsersWithTopStyle.
func (mr *MockSearchQuerierMockRecorder) SearchUsersWithTopStyle(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersWithTopStyle", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsersWithTopStyle), ctx, db, arg)
}
