// Code generated by MockGen. DO NOT EDIT.
// Source: users.sql.go
//
// Generated by this command:
//
//	mockgen -source=users.sql.go -destination=mock/users.sql.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dbpostgres "example/dbpostgres"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsersQuerier is a mock of UsersQuerier interface.
type MockUsersQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockUsersQuerierMockRecorder
	isgomock struct{}
}

// MockUsersQuerierMockRecorder is the mock recorder for MockUsersQuerier.
type MockUsersQuerierMockRecorder struct {
	mock *MockUsersQuerier
}

// NewMockUsersQuerier creates a new mock instance.
func NewMockUsersQuerier(ctrl *gomock.Controller) *MockUsersQuerier {
	mock := &MockUsersQuerier{ctrl: ctrl}
	mock.recorder = &MockUsersQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersQuerier) EXPECT() *MockUsersQuerierMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUsersQuerier) CreateUser(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.CreateUserParams) (*dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, db, arg)
	ret0, _ := ret[0].(*dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsersQuerierMockRecorder) CreateUser(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsersQuerier)(nil).CreateUser), ctx, db, arg)
}

// DeleteUser mocks base method.
func (m *MockUsersQuerier) DeleteUser(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.DeleteUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, db, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUsersQuerierMockRecorder) DeleteUser(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUsersQuerier)(nil).DeleteUser), ctx, db, arg)
}

// GetUser mocks base method.
func (m *MockUsersQuerier) GetUser(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.GetUserParams) (*dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, db, arg)
	ret0, _ := ret[0].(*dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUsersQuerierMockRecorder) GetUser(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUsersQuerier)(nil).GetUser), ctx, db, arg)
}

// ListUsers mocks base method.
func (m *MockUsersQuerier) ListUsers(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.ListUsersParams) ([]dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, db, arg)
	ret0, _ := ret[0].([]dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUsersQuerierMockRecorder) ListUsers(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUsersQuerier)(nil).ListUsers), ctx, db, arg)
}

// UpdateUser mocks base method.
func (m *MockUsersQuerier) UpdateUser(ctx context.Context, db dbpostgres.DBTX, arg dbpostgres.UpdateUserParams) (*dbpostgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, db, arg)
	ret0, _ := ret[0].(*dbpostgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUsersQuerierMockRecorder) UpdateUser(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUsersQuerier)(nil).UpdateUser), ctx, db, arg)
}
