// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lock.sql

package dbmysql

import (
	"context"
)

const getUserWithLock = `-- name: GetUserWithLock :one
SELECT id, name, email, created_at, phone
FROM users
WHERE id = ?
LIMIT 1
FOR UPDATE -- :if $2
`

var _getUserWithLockDynQ = dynCompile(getUserWithLock)

type GetUserWithLockParams struct {
	ID   int64
	Lock bool
}

func (q *Queries) GetUserWithLock(ctx context.Context, arg GetUserWithLockParams) (User, error) {

	dynQuery, dynArgs := _getUserWithLockDynQ.Build([]any{arg.ID, arg.Lock})
	row := q.db.QueryRowContext(ctx, dynQuery, dynArgs...)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	return i, err
}
