// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmysql

import (
	"database/sql"
	"time"
)

type FilterItem struct {
	ID   int64
	Kind string
	A    string
	B    string
	C    string
}

type Order struct {
	ID        int64
	UserID    int64
	Amount    string
	Status    string
	CreatedAt time.Time
}

type Product struct {
	ID        int64
	Name      sql.NullString
	Price     string
	Stock     sql.NullInt32
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt time.Time
	Phone     sql.NullString
}
