// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbmysql

import (
	"context"
)

const searchFilterItems = `-- name: SearchFilterItems :many
SELECT id
FROM filter_items
WHERE kind = ?
  AND id IN (/*SLICE:ids*/?2) -- :if $2
`

var _searchFilterItemsDynQ = dynCompile(searchFilterItems)

type SearchFilterItemsParams struct {
	Kind string
	Ids  []int64
}

func (q *Queries) SearchFilterItems(ctx context.Context, arg SearchFilterItemsParams) ([]int64, error) {

	dynQuery, dynArgs := _searchFilterItemsDynQ.Build([]any{arg.Kind, arg.Ids})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
