// Code generated by MockGen. DO NOT EDIT.
// Source: orders.sql.go
//
// Generated by this command:
//
//	mockgen -source=orders.sql.go -destination=mock/orders.sql.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	db "example/db"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdersQuerier is a mock of OrdersQuerier interface.
type MockOrdersQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersQuerierMockRecorder
	isgomock struct{}
}

// MockOrdersQuerierMockRecorder is the mock recorder for MockOrdersQuerier.
type MockOrdersQuerierMockRecorder struct {
	mock *MockOrdersQuerier
}

// NewMockOrdersQuerier creates a new mock instance.
func NewMockOrdersQuerier(ctrl *gomock.Controller) *MockOrdersQuerier {
	mock := &MockOrdersQuerier{ctrl: ctrl}
	mock.recorder = &MockOrdersQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersQuerier) EXPECT() *MockOrdersQuerierMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrdersQuerier) CreateOrder(ctx context.Context, arg1 db.DBTX, arg db.CreateOrderParams) (*db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, arg1, arg)
	ret0, _ := ret[0].(*db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrdersQuerierMockRecorder) CreateOrder(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrdersQuerier)(nil).CreateOrder), ctx, arg1, arg)
}

// GetOrder mocks base method.
func (m *MockOrdersQuerier) GetOrder(ctx context.Context, arg1 db.DBTX, arg db.GetOrderParams) (*db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, arg1, arg)
	ret0, _ := ret[0].(*db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrdersQuerierMockRecorder) GetOrder(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrdersQuerier)(nil).GetOrder), ctx, arg1, arg)
}

// GetUserOrderSummary mocks base method.
func (m *MockOrdersQuerier) GetUserOrderSummary(ctx context.Context, arg1 db.DBTX, arg db.GetUserOrderSummaryParams) (*db.GetUserOrderSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrderSummary", ctx, arg1, arg)
	ret0, _ := ret[0].(*db.GetUserOrderSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrderSummary indicates an expected call of GetUserOrderSummary.
func (mr *MockOrdersQuerierMockRecorder) GetUserOrderSummary(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrderSummary", reflect.TypeOf((*MockOrdersQuerier)(nil).GetUserOrderSummary), ctx, arg1, arg)
}

// ListOrdersByUser mocks base method.
func (m *MockOrdersQuerier) ListOrdersByUser(ctx context.Context, arg1 db.DBTX, arg db.ListOrdersByUserParams) ([]*db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByUser", ctx, arg1, arg)
	ret0, _ := ret[0].([]*db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrdersByUser indicates an expected call of ListOrdersByUser.
func (mr *MockOrdersQuerierMockRecorder) ListOrdersByUser(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByUser", reflect.TypeOf((*MockOrdersQuerier)(nil).ListOrdersByUser), ctx, arg1, arg)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrdersQuerier) UpdateOrderStatus(ctx context.Context, arg1 db.DBTX, arg db.UpdateOrderStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, arg1, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrdersQuerierMockRecorder) UpdateOrderStatus(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrdersQuerier)(nil).UpdateOrderStatus), ctx, arg1, arg)
}
