// Code generated by MockGen. DO NOT EDIT.
// Source: product.sql.go
//
// Generated by this command:
//
//	mockgen -source=product.sql.go -destination=mock/product.sql.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	db "example/db"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockProductQuerier is a mock of ProductQuerier interface.
type MockProductQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockProductQuerierMockRecorder
	isgomock struct{}
}

// MockProductQuerierMockRecorder is the mock recorder for MockProductQuerier.
type MockProductQuerierMockRecorder struct {
	mock *MockProductQuerier
}

// NewMockProductQuerier creates a new mock instance.
func NewMockProductQuerier(ctrl *gomock.Controller) *MockProductQuerier {
	mock := &MockProductQuerier{ctrl: ctrl}
	mock.recorder = &MockProductQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductQuerier) EXPECT() *MockProductQuerierMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductQuerier) CreateProduct(ctx context.Context, arg1 db.DBTX, arg db.CreateProductParams) (*db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, arg1, arg)
	ret0, _ := ret[0].(*db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductQuerierMockRecorder) CreateProduct(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductQuerier)(nil).CreateProduct), ctx, arg1, arg)
}

// DeleteProduct mocks base method.
func (m *MockProductQuerier) DeleteProduct(ctx context.Context, arg1 db.DBTX, arg db.DeleteProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, arg1, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductQuerierMockRecorder) DeleteProduct(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductQuerier)(nil).DeleteProduct), ctx, arg1, arg)
}

// GetProduct mocks base method.
func (m *MockProductQuerier) GetProduct(ctx context.Context, arg1 db.DBTX, arg db.GetProductParams) (*db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, arg1, arg)
	ret0, _ := ret[0].(*db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductQuerierMockRecorder) GetProduct(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductQuerier)(nil).GetProduct), ctx, arg1, arg)
}

// GetProductPrice mocks base method.
func (m *MockProductQuerier) GetProductPrice(ctx context.Context, arg1 db.DBTX, arg db.GetProductPriceParams) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductPrice", ctx, arg1, arg)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductPrice indicates an expected call of GetProductPrice.
func (mr *MockProductQuerierMockRecorder) GetProductPrice(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductPrice", reflect.TypeOf((*MockProductQuerier)(nil).GetProductPrice), ctx, arg1, arg)
}

// GetProductsInStock mocks base method.
func (m *MockProductQuerier) GetProductsInStock(ctx context.Context, arg1 db.DBTX) (*int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsInStock", ctx, arg1)
	ret0, _ := ret[0].(*int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsInStock indicates an expected call of GetProductsInStock.
func (mr *MockProductQuerierMockRecorder) GetProductsInStock(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsInStock", reflect.TypeOf((*MockProductQuerier)(nil).GetProductsInStock), ctx, arg1)
}

// ListProducts mocks base method.
func (m *MockProductQuerier) ListProducts(ctx context.Context, arg1 db.DBTX) ([]*db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, arg1)
	ret0, _ := ret[0].([]*db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockProductQuerierMockRecorder) ListProducts(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockProductQuerier)(nil).ListProducts), ctx, arg1)
}

// UpdateProductStock mocks base method.
func (m *MockProductQuerier) UpdateProductStock(ctx context.Context, arg1 db.DBTX, arg db.UpdateProductStockParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStock", ctx, arg1, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductStock indicates an expected call of UpdateProductStock.
func (mr *MockProductQuerierMockRecorder) UpdateProductStock(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStock", reflect.TypeOf((*MockProductQuerier)(nil).UpdateProductStock), ctx, arg1, arg)
}
