// Code generated by sqlc. DO NOT EDIT.

package dbpostgres

import (
	"reflect"
	"strings"
)

// Engine/driver-specific lexing and output rules, fixed at generation time.

// dynQuestionMarkPlaceholders is true for MySQL's positional protocol: Build
// emits '?' output placeholders and bare '?' input markers are numbered by
// order of appearance.
const dynQuestionMarkPlaceholders = false

// dynNumberedQuestionMarks is true for engines whose SQL text carries numbered
// ?N input markers (SQLite ?N parameters; MySQL sqlc.slice markers numbered at
// generation time). PostgreSQL keeps '?' strictly as operator text.
const dynNumberedQuestionMarks = false

// dynBracketIdentifiers is true for engines where [name] is a quoted identifier
// (SQLite) rather than a subscript such as PostgreSQL's arr[$1].
const dynBracketIdentifiers = false

// dynPostgresDialect enables PostgreSQL-specific lexing: dollar-quoted strings
// ($$...$$ / $tag$...$tag$), E'...' escape strings, and nested block comments.
const dynPostgresDialect = true

// dynBackslashStringEscapes is true when a backslash escapes the next character
// inside '...' and "..." literals (MySQL's default sql_mode).
const dynBackslashStringEscapes = false

// dynCompiledSeg is one segment of a pre-compiled dynamic SQL query.
type dynCompiledSeg struct {
	// parts splits the segment text at each numbered $N or ?N input placeholder.
	// Build renders active placeholders as sequential output placeholders.
	// len(parts) == len(argNums)+1
	parts []string
	// argNums are the 1-based input SQL parameter numbers in order of appearance.
	// args[argNums[i]-1] provides the value for the corresponding placeholder.
	argNums []int
	// condIdxs are 0-based indices into the args slice passed to Build.
	// All referenced args must be "active" (non-nil pointer / true bool)
	// for this segment to be included. Empty means always include.
	condIdxs []int
}

// dynCompiledQuery is a pre-parsed dynamic SQL query.
// Create one at package level with dynCompile and reuse it across calls.
type dynCompiledQuery struct {
	segs []dynCompiledSeg
}

// dynCompile parses an annotated SQL string (containing -- :if $N markers)
// into a dynCompiledQuery. Call this once at package initialisation time
// and store the result in a package-level variable.
func dynCompile(annotatedSQL string) *dynCompiledQuery {
	var segs []dynCompiledSeg
	var staticBuf strings.Builder
	nextArgNum := 1

	flushStatic := func() {
		if staticBuf.Len() == 0 {
			return
		}
		parts, argNums := dynSplitPlaceholders(staticBuf.String(), &nextArgNum)
		segs = append(segs, dynCompiledSeg{parts: parts, argNums: argNums})
		staticBuf.Reset()
	}

	rest := annotatedSQL
	firstLine := true
	var lex dynLexState

	for rest != "" {
		var line string
		if i := strings.IndexByte(rest, '\n'); i >= 0 {
			line, rest = rest[:i], rest[i+1:]
		} else {
			line, rest = rest, ""
		}

		sep := "\n"
		if firstLine {
			sep = ""
			firstLine = false
		}

		// A line that begins inside a string literal, dollar-quoted string, or
		// block comment left open by a previous line is continuation text: any
		// annotation-shaped text on it is string/comment content, so the line
		// goes straight to the static buffer unscanned.
		if lex.open() {
			lex = dynLineEndState(line, lex)
			staticBuf.WriteString(sep)
			staticBuf.WriteString(line)
			continue
		}

		trimmed := strings.TrimSpace(line)

		// Standalone block annotation: "-- :if $N" — the next line is conditional.
		if after, ok := strings.CutPrefix(trimmed, "-- :if $"); ok && after != "" {
			n := dynParseInt(after, len(after))
			if n > 0 {
				flushStatic()
				condIdx := n - 1
				// Read and process next line.
				if rest != "" {
					var nextLine string
					if i := strings.IndexByte(rest, '\n'); i >= 0 {
						nextLine, rest = rest[:i], rest[i+1:]
					} else {
						nextLine, rest = rest, ""
					}
					condIdxs, cleaned := dynExtractCondIdxs(nextLine)
					condIdxs = append([]int{condIdx}, condIdxs...)
					lex = dynLineEndState(cleaned, lex)
					parts, argNums := dynSplitPlaceholders("\n"+cleaned, &nextArgNum)
					segs = append(segs, dynCompiledSeg{
						parts:    parts,
						argNums:  argNums,
						condIdxs: condIdxs,
					})
				}
				continue
			}
		}

		// Inline annotation(s): "text -- :if $N [-- :if $M ...]"
		if condIdxs, cleaned := dynExtractCondIdxs(line); len(condIdxs) > 0 {
			flushStatic()
			lex = dynLineEndState(cleaned, lex)
			parts, argNums := dynSplitPlaceholders(sep+cleaned, &nextArgNum)
			segs = append(segs, dynCompiledSeg{
				parts:    parts,
				argNums:  argNums,
				condIdxs: condIdxs,
			})
			continue
		}

		// Unconditional line: accumulate into the static buffer.
		lex = dynLineEndState(line, lex)
		staticBuf.WriteString(sep)
		staticBuf.WriteString(line)
	}

	flushStatic()
	return &dynCompiledQuery{segs: segs}
}

// dynLexState is the lexical construct left open at the end of a source line,
// carried across lines so continuation text is never scanned for markers.
type dynLexState struct {
	quote     byte   // open quoted span: '\'', '"', '`' or '[' (0 = none)
	backslash bool   // backslash escapes apply inside the open quote
	comment   int    // open block-comment depth
	dollar    string // open dollar-quote delimiter (e.g. "$tag$"), "" = none
}

func (s dynLexState) open() bool {
	return s.quote != 0 || s.comment > 0 || s.dollar != ""
}

// dynLineEndState scans one line and returns the lexical state open at its
// end. Line comments never carry across lines, so "-- ..." ends the scan.
func dynLineEndState(line string, st dynLexState) dynLexState {
	i := 0
	for i < len(line) {
		switch {
		case st.dollar != "":
			j := strings.Index(line[i:], st.dollar)
			if j < 0 {
				return st
			}
			i += j + len(st.dollar)
			st.dollar = ""
		case st.comment > 0:
			for i < len(line) && st.comment > 0 {
				switch {
				case dynPostgresDialect && i+1 < len(line) && line[i] == '/' && line[i+1] == '*':
					st.comment++
					i += 2
				case i+1 < len(line) && line[i] == '*' && line[i+1] == '/':
					st.comment--
					i += 2
				default:
					i++
				}
			}
			if st.comment > 0 {
				return st
			}
		case st.quote == '[':
			j := strings.IndexByte(line[i:], ']')
			if j < 0 {
				return st
			}
			i += j + 1
			st.quote = 0
		case st.quote != 0:
			j, closed := dynQuoteEnd(line, i, st.quote, st.backslash)
			if !closed {
				return st
			}
			i = j
			st.quote = 0
		default:
			c := line[i]
			if c == '-' && i+1 < len(line) && line[i+1] == '-' {
				return st
			}
			if c == '/' && i+1 < len(line) && line[i+1] == '*' {
				st.comment = 1
				i += 2
				continue
			}
			if c == '\'' || c == '"' || c == '`' {
				st.quote = c
				st.backslash = c != '`' && (dynBackslashStringEscapes ||
					(dynPostgresDialect && c == '\'' && dynEscapeStringPrefix(line, i)))
				i++
				continue
			}
			if c == '[' && dynBracketIdentifiers {
				st.quote = '['
				i++
				continue
			}
			if c == '$' && dynPostgresDialect {
				if d := dynDollarDelim(line, i); d != "" {
					st.dollar = d
					i += len(d)
					continue
				}
			}
			i++
		}
	}
	return st
}

// Build applies the pre-compiled filter to args and returns the final SQL
// and the trimmed args slice. The method is safe to call concurrently.
//
// Numbered output placeholders reuse repeated input parameters. MySQL uses
// positional question-mark placeholders, so repeated parameters are repeated.
func (q *dynCompiledQuery) Build(args []any) (string, []any) {
	var b strings.Builder
	var outArgs []any
	n := 1
	// Numbered-placeholder drivers reuse one output placeholder per repeated
	// input parameter; MySQL is positional, so repeats are re-emitted and no
	// reuse bookkeeping is kept at all.
	var argIdxToN map[int]int      // input argIdx (0-based) -> output $N
	var sliceIdxToNs map[int][]int // input argIdx -> expanded slice output $Ns
	if !dynQuestionMarkPlaceholders {
		argIdxToN = make(map[int]int)
	}

	for _, seg := range q.segs {
		// Check all conditions.
		active := true
		for _, idx := range seg.condIdxs {
			if idx >= len(args) || !dynArgActive(args[idx]) {
				active = false
				break
			}
		}
		if !active {
			continue
		}

		// Write text parts interleaved with driver-appropriate placeholders.
		for i, part := range seg.parts {
			if before, isSlice := dynSlicePrefix(part); isSlice && i < len(seg.argNums) {
				argIdx := seg.argNums[i] - 1
				if argIdx >= len(args) {
					b.WriteString(before)
					b.WriteString("NULL")
					continue
				}
				if v := reflect.ValueOf(args[argIdx]); v.Kind() == reflect.Slice {
					b.WriteString(before)
					if dynQuestionMarkPlaceholders {
						dynWriteSlice(&b, &outArgs, v, &n)
					} else if existing, ok := sliceIdxToNs[argIdx]; ok {
						// Same slice already expanded; replay its placeholders.
						dynWritePlaceholders(&b, existing)
					} else {
						if sliceIdxToNs == nil {
							sliceIdxToNs = make(map[int][]int)
						}
						sliceIdxToNs[argIdx] = dynWriteSlice(&b, &outArgs, v, &n)
					}
					continue
				}
				// The arg is not a slice: the "/*SLICE:...*/" text is ordinary
				// comment content, so keep it and bind a scalar placeholder.
			}
			b.WriteString(part)
			if i < len(seg.argNums) {
				argIdx := seg.argNums[i] - 1
				if existing, ok := argIdxToN[argIdx]; ok {
					// Same input parameter already emitted; reuse its output placeholder.
					dynWritePlaceholder(&b, existing)
				} else {
					dynWritePlaceholder(&b, n)
					if argIdxToN != nil {
						argIdxToN[argIdx] = n
					}
					n++
					if argIdx < len(args) {
						outArgs = append(outArgs, args[argIdx])
					}
				}
			}
		}
	}

	return dynFinalizeQuery(b.String()), outArgs
}

// dynWritePlaceholders replays the placeholders of an already-expanded slice.
// A nil list means the slice rendered as NULL; replay NULL, not nothing.
func dynWritePlaceholders(b *strings.Builder, nums []int) {
	if len(nums) == 0 {
		b.WriteString("NULL")
		return
	}
	for i, n := range nums {
		if i > 0 {
			b.WriteByte(',')
		}
		dynWritePlaceholder(b, n)
	}
}

func dynWritePlaceholder(b *strings.Builder, n int) {
	if dynQuestionMarkPlaceholders {
		b.WriteByte('?')
		return
	}
	b.WriteByte('$')
	dynWriteInt(b, n)
}

func dynSlicePrefix(part string) (string, bool) {
	start := strings.LastIndex(part, "/*SLICE:")
	if start == -1 || !strings.HasSuffix(part, "*/") {
		return part, false
	}
	return part[:start], true
}

// dynWriteSlice expands a slice arg into comma-separated placeholders and
// returns their output numbers. Empty slices render as NULL (matching sqlc's
// non-dynamic sqlc.slice() expansion) and return nil.
func dynWriteSlice(b *strings.Builder, outArgs *[]any, values reflect.Value, n *int) []int {
	ln := values.Len()
	if ln == 0 {
		b.WriteString("NULL")
		return nil
	}
	nums := make([]int, ln)
	for i := range ln {
		if i > 0 {
			b.WriteByte(',')
		}
		nums[i] = *n
		dynWritePlaceholder(b, *n)
		*n++
		*outArgs = append(*outArgs, values.Index(i).Interface())
	}
	return nums
}

// dynExtractCondIdxs extracts all " -- :if $N" annotations from line,
// returning the 0-based condition indices and the cleaned line text.
func dynExtractCondIdxs(line string) (condIdxs []int, cleaned string) {
	idx := dynAnnotationStart(line)
	if idx == -1 {
		return nil, line
	}
	cleaned = strings.TrimRight(line[:idx], " \t")
	tail := line[idx:]
	for {
		i := strings.Index(tail, " -- :if $")
		if i == -1 {
			break
		}
		numStart := i + 9 // len(" -- :if $")
		numEnd := numStart
		for numEnd < len(tail) && tail[numEnd] >= '0' && tail[numEnd] <= '9' {
			numEnd++
		}
		if numEnd > numStart {
			if n := dynParseInt(tail[numStart:numEnd], numEnd-numStart); n > 0 {
				condIdxs = append(condIdxs, n-1)
			}
		}
		tail = tail[i+1:]
	}
	return condIdxs, cleaned
}

// dynAnnotationStart returns the index of the leading space of the first
// " -- :if $N" annotation in line that lies in SQL-code context, or -1 if there
// is none. String literals, quoted identifiers, and block comments are skipped
// so marker-looking text inside them (e.g. '... -- :if $1') is never mistaken
// for an annotation. Line comments are intentionally transparent: a manual
// "-- note" written before the generated "-- :if $N" marker must not hide it.
func dynAnnotationStart(line string) int {
	const marker = " -- :if $"
	inLineComment := false
	i := 0
	for i < len(line) {
		if strings.HasPrefix(line[i:], marker) {
			return i
		}
		if inLineComment {
			i++
			continue
		}
		if line[i] == '-' && i+1 < len(line) && line[i+1] == '-' {
			// Everything to end of line is now comment text; stop parsing
			// strings/identifiers so their delimiters do not swallow the marker.
			inLineComment = true
			i += 2
			continue
		}
		if j := dynSkipQuotedOrBlock(line, i); j > i {
			i = j
			continue
		}
		i++
	}
	return -1
}

// dynSplitPlaceholders splits text at numbered $N and ?N input placeholders that
// appear in SQL-code context. For MySQL, bare ? input placeholders are numbered
// by appearance; numbered ?N markers are only recognized on engines that use
// them (SQLite, MySQL). Bare markers and any markers inside string literals,
// quoted identifiers, or comments are preserved verbatim; Build emits
// driver-appropriate output placeholders.
// Returns parts (len = len(argNums)+1) and 1-based argNums.
func dynSplitPlaceholders(text string, nextArgNum *int) (parts []string, argNums []int) {
	partStart := 0
	i := 0
	for i < len(text) {
		// Skip string literals, quoted identifiers, and comments verbatim; they
		// stay inside the current part so a marker within them is never rewritten.
		if k := dynSkipToken(text, i); k > i {
			i = k
			continue
		}
		c := text[i]
		if c != '$' && c != '?' {
			i++
			continue
		}
		j := i + 1
		for j < len(text) && text[j] >= '0' && text[j] <= '9' {
			j++
		}
		n := 0
		switch {
		case j > i+1 && (c == '$' || dynNumberedQuestionMarks):
			n = dynParseInt(text[i+1:j], j-i-1)
		case dynQuestionMarkPlaceholders && c == '?':
			n = *nextArgNum
		default:
			// Bare '$', PostgreSQL's '?' operators, or ?N text on an engine
			// without numbered ? parameters: not a bind placeholder.
			i = j
			continue
		}
		if n <= 0 {
			i = j
			continue
		}
		if dynQuestionMarkPlaceholders && n >= *nextArgNum {
			*nextArgNum = n + 1
		}
		parts = append(parts, text[partStart:i])
		argNums = append(argNums, n)
		partStart = j
		i = j
	}
	parts = append(parts, text[partStart:])
	return parts, argNums
}

// dynSkipToken reports the index just past a SQL string literal, quoted
// identifier, or comment (line or block) beginning at text[i]. It returns i
// unchanged when text[i] does not begin one, so the caller advances by a byte.
func dynSkipToken(text string, i int) int {
	if text[i] == '-' && i+1 < len(text) && text[i+1] == '-' {
		if j := strings.IndexByte(text[i:], '\n'); j >= 0 {
			return i + j
		}
		return len(text)
	}
	return dynSkipQuotedOrBlock(text, i)
}

// dynSkipQuotedOrBlock skips a string literal, quoted identifier, dollar-quoted
// string, or block comment beginning at text[i], returning i unchanged for
// anything else. Line comments are handled by dynSkipToken so callers scanning
// for annotations can keep them transparent.
func dynSkipQuotedOrBlock(text string, i int) int {
	switch c := text[i]; c {
	case '\'':
		esc := dynBackslashStringEscapes ||
			(dynPostgresDialect && dynEscapeStringPrefix(text, i))
		j, _ := dynQuoteEnd(text, i+1, c, esc)
		return j
	case '"':
		j, _ := dynQuoteEnd(text, i+1, c, dynBackslashStringEscapes)
		return j
	case '`':
		j, _ := dynQuoteEnd(text, i+1, c, false)
		return j
	case '[':
		if dynBracketIdentifiers {
			if j := strings.IndexByte(text[i+1:], ']'); j >= 0 {
				return i + 1 + j + 1
			}
			return len(text)
		}
	case '$':
		if dynPostgresDialect {
			if d := dynDollarDelim(text, i); d != "" {
				if j := strings.Index(text[i+len(d):], d); j >= 0 {
					return i + len(d) + j + len(d)
				}
				return len(text)
			}
		}
	case '/':
		if i+1 < len(text) && text[i+1] == '*' {
			return dynSkipBlockComment(text, i)
		}
	}
	return i
}

// dynQuoteEnd scans from i (already inside a span quoted by q) to its closing
// delimiter. The SQL doubling escape keeps the span open; when backslash is
// set (MySQL strings, PostgreSQL E” strings), a backslash escapes the next
// byte. Returns the index just past the close and whether the span closed.
func dynQuoteEnd(text string, i int, q byte, backslash bool) (int, bool) {
	for j := i; j < len(text); j++ {
		c := text[j]
		if backslash && c == '\\' {
			j++
			continue
		}
		if c != q {
			continue
		}
		if j+1 < len(text) && text[j+1] == q {
			j++ // doubled delimiter escape: consume both, stay open
			continue
		}
		return j + 1, true
	}
	return len(text), false
}

// dynEscapeStringPrefix reports whether the quote at text[i] is opened by a
// PostgreSQL E'...' escape-string prefix (an E/e that is itself not the tail
// of a longer identifier).
func dynEscapeStringPrefix(text string, i int) bool {
	if i == 0 || (text[i-1] != 'e' && text[i-1] != 'E') {
		return false
	}
	if i == 1 {
		return true
	}
	p := text[i-2]
	return !(p == '_' || p == '$' ||
		(p >= '0' && p <= '9') || (p >= 'a' && p <= 'z') || (p >= 'A' && p <= 'Z'))
}

// dynDollarDelim returns the PostgreSQL dollar-quote delimiter starting at
// text[i] ("$$" or "$tag$"), or "" when text[i] does not open one (e.g. the
// bind placeholder $1 — tags cannot start with a digit).
func dynDollarDelim(text string, i int) string {
	for j := i + 1; j < len(text); j++ {
		c := text[j]
		if c == '$' {
			return text[i : j+1]
		}
		ident := c == '_' || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(j > i+1 && c >= '0' && c <= '9')
		if !ident {
			return ""
		}
	}
	return ""
}

// dynSkipBlockComment returns the index just past the block comment starting
// at text[i] (text[i:i+2] == "/*"). PostgreSQL block comments nest; other
// engines end at the first "*/". Unterminated comments run to end of text.
func dynSkipBlockComment(text string, i int) int {
	depth := 0
	for j := i; j < len(text); j++ {
		if j+1 >= len(text) {
			break
		}
		if text[j] == '/' && text[j+1] == '*' && (dynPostgresDialect || depth == 0) {
			depth++
			j++
			continue
		}
		if text[j] == '*' && text[j+1] == '/' {
			depth--
			j++
			if depth == 0 {
				return j + 1
			}
		}
	}
	return len(text)
}

// dynFinalizeQuery cleans up the output SQL after conditional lines have been
// removed. It loops until stable, handling cascading cases such as:
//   - trailing comma on the new last line  → strip the comma
//   - orphaned clause keyword (WHERE, ORDER BY, GROUP BY, HAVING) → remove it
func dynFinalizeQuery(query string) string {
	for {
		// Find the end of the last non-empty line.
		end := len(query)
		for end > 0 && (query[end-1] == ' ' || query[end-1] == '\t' || query[end-1] == '\n') {
			end--
		}
		if end == 0 {
			return query
		}
		// Find start of last non-empty line.
		start := end
		for start > 0 && query[start-1] != '\n' {
			start--
		}
		trimmed := strings.TrimSpace(query[start:end])

		// Strip trailing comma.
		if len(trimmed) > 0 && trimmed[len(trimmed)-1] == ',' {
			commaPos := strings.LastIndexByte(query[start:end], ',')
			if commaPos >= 0 {
				query = query[:start+commaPos] + query[start+commaPos+1:]
			}
			continue // re-evaluate after removal
		}

		// Remove orphaned SQL clause keywords.
		if strings.EqualFold(trimmed, "ORDER BY") ||
			strings.EqualFold(trimmed, "WHERE") ||
			strings.EqualFold(trimmed, "GROUP BY") ||
			strings.EqualFold(trimmed, "HAVING") {
			newEnd := start
			for newEnd > 0 && (query[newEnd-1] == '\n' || query[newEnd-1] == ' ' || query[newEnd-1] == '\t') {
				newEnd--
			}
			query = query[:newEnd]
			continue // re-evaluate after removal
		}

		break // nothing changed
	}
	return query
}

// DynSQL is a pre-compiled dynamic SQL query.
// Use CompileDynSQL to create one at package level for maximum performance.
type DynSQL = dynCompiledQuery

// CompileDynSQL parses an annotated SQL string (containing -- :if $N markers)
// once and returns a *DynSQL whose Build method can be called repeatedly
// with no per-call string scanning.
func CompileDynSQL(annotatedSQL string) *DynSQL {
	return dynCompile(annotatedSQL)
}

// DynamicSQL processes a SQL query with -- :if $N annotations at runtime.
// Prefer dynCompile + Build for repeated calls; DynamicSQL is provided for
// one-off use and backward compatibility.
//
// For each annotated line, it checks args[N-1] (N is 1-based, matching $N):
//   - nil pointer → skip the line
//   - false bool  → skip the line
//   - nil slice   → skip the line (an empty non-nil slice keeps it and
//     renders NULL, matching zero rows; see NilableSlice)
//   - otherwise   → keep the line
//
// After filtering, remaining placeholders are renumbered sequentially and
// the args slice is trimmed to match, so the query is always valid.
func DynamicSQL(query string, args []any) (string, []any) {
	return dynCompile(query).Build(args)
}

// NilableSlice converts an empty slice to nil so a :if-gated slice condition
// is skipped ("don't filter") instead of kept (IN (NULL), matching zero
// rows). Use it at the call site when "no values supplied" means "no filter".
func NilableSlice[T any](s []T) []T {
	if len(s) == 0 {
		return nil
	}
	return s
}

// dynParseInt parses a non-negative integer from s[0:length] without allocations.
// Returns -1 if the string contains non-digit characters.
func dynParseInt(s string, length int) int {
	n := 0
	for i := 0; i < length; i++ {
		c := s[i]
		if c < '0' || c > '9' {
			return -1
		}
		n = n*10 + int(c-'0')
	}
	return n
}

// dynWriteInt writes a positive integer to buf without allocations for values < 10.
func dynWriteInt(buf *strings.Builder, n int) {
	if n < 10 {
		buf.WriteByte(byte('0' + n))
	} else if n < 100 {
		buf.WriteByte(byte('0' + n/10))
		buf.WriteByte(byte('0' + n%10))
	} else {
		var tmp [20]byte
		i := len(tmp)
		for n > 0 {
			i--
			tmp[i] = byte('0' + n%10)
			n /= 10
		}
		buf.Write(tmp[i:])
	}
}

func dynArgActive(arg any) bool {
	if arg == nil {
		return false
	}
	switch v := arg.(type) {
	case bool:
		return v
	case *string:
		return v != nil
	case *int:
		return v != nil
	case *int32:
		return v != nil
	case *int64:
		return v != nil
	case *float64:
		return v != nil
	case *bool:
		return v != nil
	}
	v := reflect.ValueOf(arg)
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return !v.IsNil()
	case reflect.Slice:
		// Only nil skips: an empty non-nil slice keeps the clause and renders
		// NULL (matches zero rows), preserving the nil/empty distinction.
		// Wrap the arg in NilableSlice when empty should mean "don't filter".
		return !v.IsNil()
	default:
		return true
	}
}
