//go:generate mockgen -source=$GOFILE -destination=mock/$GOFILE -package=mock

// Code generated by sqlc. DO NOT EDIT.
// source: filter.sql

package dbpostgres

import (
	"context"

	tracing "example"
)

func NewFilterQueries() *FilterQueries {
	return &FilterQueries{}
}

type FilterQueries struct {
}

const ListFilterItems = `-- name: ListFilterItems :many
SELECT id, a, b, c
FROM filter_items
WHERE a = $1
  AND b = $2 -- :if $2
  AND c = $3
ORDER BY id
`

var _listFilterItemsDynQ = dynCompile(ListFilterItems)

type ListFilterItemsParams struct {
	A string
	B *string
	C string
}

type ListFilterItemsRow struct {
	ID int64
	A  string
	B  string
	C  string
}

// An optional filter in the middle of the WHERE clause: dropping @b renumbers
// the placeholder for @c.
func (q *FilterQueries) ListFilterItems(ctx context.Context, db DBTX, arg ListFilterItemsParams) ([]ListFilterItemsRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "FilterQueries.ListFilterItems")
	defer tracer.End()
	dynQuery, dynArgs := _listFilterItemsDynQ.Build([]any{arg.A, arg.B, arg.C})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilterItemsRow
	for rows.Next() {
		var i ListFilterItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.A,
			&i.B,
			&i.C,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchFilterItems = `-- name: SearchFilterItems :many
SELECT id
FROM filter_items
WHERE kind = $1
  AND id = ANY($2::bigint[]) -- :if $2
ORDER BY id
`

var _searchFilterItemsDynQ = dynCompile(SearchFilterItems)

type SearchFilterItemsParams struct {
	Kind string
	Ids  []int64
}

func (q *FilterQueries) SearchFilterItems(ctx context.Context, db DBTX, arg SearchFilterItemsParams) ([]int64, error) {
	ctx, tracer := tracing.StartTracing(ctx, "FilterQueries.SearchFilterItems")
	defer tracer.End()
	dynQuery, dynArgs := _searchFilterItemsDynQ.Build([]any{arg.Kind, arg.Ids})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type FilterQuerier interface {
	// An optional filter in the middle of the WHERE clause: dropping @b renumbers
	// the placeholder for @c.
	ListFilterItems(ctx context.Context, db DBTX, arg ListFilterItemsParams) ([]ListFilterItemsRow, error)
	SearchFilterItems(ctx context.Context, db DBTX, arg SearchFilterItemsParams) ([]int64, error)
}

var _ FilterQuerier = (*FilterQueries)(nil)
