//go:generate mockgen -source=$GOFILE -destination=mock/$GOFILE -package=mock

// Code generated by sqlc. DO NOT EDIT.
// source: lock.sql

package dbpostgres

import (
	"context"
	"errors"

	tracing "example"
	"github.com/jackc/pgx/v5"
)

func NewLockQueries() *LockQueries {
	return &LockQueries{}
}

type LockQueries struct {
}

const GetUserWithLock = `-- name: GetUserWithLock :one
SELECT id, name, email, created_at, phone
FROM users
WHERE id = $1
LIMIT 1
FOR UPDATE -- :if $2
`

var _getUserWithLockDynQ = dynCompile(GetUserWithLock)

type GetUserWithLockParams struct {
	ID   int64
	Lock bool
}

func (q *LockQueries) GetUserWithLock(ctx context.Context, db DBTX, arg GetUserWithLockParams) (*User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "LockQueries.GetUserWithLock")
	defer tracer.End()
	dynQuery, dynArgs := _getUserWithLockDynQ.Build([]any{arg.ID, arg.Lock})
	row := db.QueryRow(ctx, dynQuery, dynArgs...)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

type LockQuerier interface {
	GetUserWithLock(ctx context.Context, db DBTX, arg GetUserWithLockParams) (*User, error)
}

var _ LockQuerier = (*LockQueries)(nil)
