//go:generate mockgen -source=$GOFILE -destination=mock/$GOFILE -package=mock

// Code generated by sqlc. DO NOT EDIT.
// source: product.sql

package dbpostgres

import (
	"context"
	"errors"

	tracing "example"
	"github.com/jackc/pgx/v5"
	decimal "github.com/shopspring/decimal"
)

func NewProductQueries() *ProductQueries {
	return &ProductQueries{}
}

type ProductQueries struct {
}

const CreateProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price, stock)
VALUES ($1, $2, $3)
RETURNING id, name, price, stock, created_at
`

type CreateProductParams struct {
	Name  *string
	Price decimal.Decimal
	Stock *int32
}

func (q *ProductQueries) CreateProduct(ctx context.Context, db DBTX, arg CreateProductParams) (*Product, error) {
	ctx, tracer := tracing.StartTracing(ctx, "ProductQueries.CreateProduct")
	defer tracer.End()
	row := db.QueryRow(ctx, CreateProduct, arg.Name, arg.Price, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
	)
	return &i, err
}

const DeleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

type DeleteProductParams struct {
	ID int64
}

func (q *ProductQueries) DeleteProduct(ctx context.Context, db DBTX, arg DeleteProductParams) error {
	ctx, tracer := tracing.StartTracing(ctx, "ProductQueries.DeleteProduct")
	defer tracer.End()
	_, err := db.Exec(ctx, DeleteProduct, arg.ID)
	return err
}

const GetProduct = `-- name: GetProduct :one
SELECT id, name, price, stock, created_at FROM products WHERE id = $1 LIMIT 1
`

type GetProductParams struct {
	ID int64
}

func (q *ProductQueries) GetProduct(ctx context.Context, db DBTX, arg GetProductParams) (*Product, error) {
	ctx, tracer := tracing.StartTracing(ctx, "ProductQueries.GetProduct")
	defer tracer.End()
	row := db.QueryRow(ctx, GetProduct, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const GetProductPrice = `-- name: GetProductPrice :one
SELECT price FROM products WHERE id = $1 LIMIT 1
`

type GetProductPriceParams struct {
	ID int64
}

func (q *ProductQueries) GetProductPrice(ctx context.Context, db DBTX, arg GetProductPriceParams) (decimal.Decimal, error) {
	ctx, tracer := tracing.StartTracing(ctx, "ProductQueries.GetProductPrice")
	defer tracer.End()
	row := db.QueryRow(ctx, GetProductPrice, arg.ID)
	var price decimal.Decimal
	err := row.Scan(&price)
	if errors.Is(err, pgx.ErrNoRows) {
		return price, nil
	}
	return price, err
}

const GetProductsInStock = `-- name: GetProductsInStock :one
SELECT stock FROM products WHERE stock > 0 LIMIT 1
`

func (q *ProductQueries) GetProductsInStock(ctx context.Context, db DBTX) (*int32, error) {
	ctx, tracer := tracing.StartTracing(ctx, "ProductQueries.GetProductsInStock")
	defer tracer.End()
	row := db.QueryRow(ctx, GetProductsInStock)
	var stock *int32
	err := row.Scan(&stock)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return stock, err
}

const ListProducts = `-- name: ListProducts :many
SELECT id, name, price, stock, created_at FROM products ORDER BY created_at DESC
`

func (q *ProductQueries) ListProducts(ctx context.Context, db DBTX) ([]Product, error) {
	ctx, tracer := tracing.StartTracing(ctx, "ProductQueries.ListProducts")
	defer tracer.End()
	rows, err := db.Query(ctx, ListProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProductStock = `-- name: UpdateProductStock :exec
UPDATE products SET stock = $2 WHERE id = $1
`

type UpdateProductStockParams struct {
	ID    int64
	Stock *int32
}

func (q *ProductQueries) UpdateProductStock(ctx context.Context, db DBTX, arg UpdateProductStockParams) error {
	ctx, tracer := tracing.StartTracing(ctx, "ProductQueries.UpdateProductStock")
	defer tracer.End()
	_, err := db.Exec(ctx, UpdateProductStock, arg.ID, arg.Stock)
	return err
}

type ProductQuerier interface {
	CreateProduct(ctx context.Context, db DBTX, arg CreateProductParams) (*Product, error)
	DeleteProduct(ctx context.Context, db DBTX, arg DeleteProductParams) error
	GetProduct(ctx context.Context, db DBTX, arg GetProductParams) (*Product, error)
	GetProductPrice(ctx context.Context, db DBTX, arg GetProductPriceParams) (decimal.Decimal, error)
	GetProductsInStock(ctx context.Context, db DBTX) (*int32, error)
	ListProducts(ctx context.Context, db DBTX) ([]Product, error)
	UpdateProductStock(ctx context.Context, db DBTX, arg UpdateProductStockParams) error
}

var _ ProductQuerier = (*ProductQueries)(nil)
