//go:generate mockgen -source=$GOFILE -destination=mock/$GOFILE -package=mock

// Code generated by sqlc. DO NOT EDIT.
// source: search.sql

package dbpostgres

import (
	"context"
	"time"

	tracing "example"
)

func NewSearchQueries() *SearchQueries {
	return &SearchQueries{}
}

type SearchQueries struct {
}

const SearchUsers = `-- name: SearchUsers :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = $1
-- :if $2
  AND email = $2
  AND phone = $3 -- :if $3
  AND EXISTS ( -- :if $5
    SELECT 1 FROM orders -- :if $5
    WHERE orders.user_id = users.id -- :if $5
      AND orders.created_at >= $4 -- :if $4 -- :if $5
  ) -- :if $5
ORDER BY id ASC
`

var _searchUsersDynQ = dynCompile(SearchUsers)

type SearchUsersParams struct {
	Name        string
	Email       *string
	Phone       *string
	OrdersSince *time.Time
	HasOrders   bool
}

func (q *SearchQueries) SearchUsers(ctx context.Context, db DBTX, arg SearchUsersParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsers")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersDynQ.Build([]any{arg.Name, arg.Email, arg.Phone, arg.OrdersSince, arg.HasOrders})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersByContact = `-- name: SearchUsersByContact :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = $1
  AND (email = $2 OR phone = $3) -- :if $2 -- :if $3
ORDER BY id ASC
`

var _searchUsersByContactDynQ = dynCompile(SearchUsersByContact)

type SearchUsersByContactParams struct {
	Name  string
	Email *string
	Phone *string
}

// Include the combined contact filter only when BOTH email AND phone are provided.
func (q *SearchQueries) SearchUsersByContact(ctx context.Context, db DBTX, arg SearchUsersByContactParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsersByContact")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersByContactDynQ.Build([]any{arg.Name, arg.Email, arg.Phone})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersByIDs = `-- name: SearchUsersByIDs :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = $1
  AND id = ANY($2::bigint[]) -- :if $2
ORDER BY id ASC
`

var _searchUsersByIDsDynQ = dynCompile(SearchUsersByIDs)

type SearchUsersByIDsParams struct {
	Name string
	Ids  []int64
}

// Filter by a list of IDs. When ids is nil the condition is skipped and all
// users matching the name are returned (nil slice = inactive filter).
func (q *SearchQueries) SearchUsersByIDs(ctx context.Context, db DBTX, arg SearchUsersByIDsParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsersByIDs")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersByIDsDynQ.Build([]any{arg.Name, arg.Ids})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersOrdered = `-- name: SearchUsersOrdered :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = $1
  AND email = $2 -- :if $2
ORDER BY
  created_at DESC, -- :if $3
  name ASC, -- :if $4
  id ASC
`

var _searchUsersOrderedDynQ = dynCompile(SearchUsersOrdered)

type SearchUsersOrderedParams struct {
	Name               string
	Email              *string
	OrderCreatedAtDesc bool
	OrderNameAsc       bool
}

func (q *SearchQueries) SearchUsersOrdered(ctx context.Context, db DBTX, arg SearchUsersOrderedParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsersOrdered")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersOrderedDynQ.Build([]any{arg.Name, arg.Email, arg.OrderCreatedAtDesc, arg.OrderNameAsc})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersOrderedByID = `-- name: SearchUsersOrderedByID :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = $1
  AND email = $2 -- :if $2
ORDER BY
  id ASC, -- :if $3
  id DESC -- :if $4
`

var _searchUsersOrderedByIDDynQ = dynCompile(SearchUsersOrderedByID)

type SearchUsersOrderedByIDParams struct {
	Name   string
	Email  *string
	IdAsc  bool
	IdDesc bool
}

func (q *SearchQueries) SearchUsersOrderedByID(ctx context.Context, db DBTX, arg SearchUsersOrderedByIDParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsersOrderedByID")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersOrderedByIDDynQ.Build([]any{arg.Name, arg.Email, arg.IdAsc, arg.IdDesc})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersWithBlock = `-- name: SearchUsersWithBlock :many
SELECT id, name, email, created_at, phone FROM users
WHERE 1 = 1
  AND ( -- :if $1
    name = $1 -- :if $1
    AND email = $1 -- :if $1
  ) -- :if $1
ORDER BY id ASC
`

var _searchUsersWithBlockDynQ = dynCompile(SearchUsersWithBlock)

type SearchUsersWithBlockParams struct {
	Name *string
}

func (q *SearchQueries) SearchUsersWithBlock(ctx context.Context, db DBTX, arg SearchUsersWithBlockParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsersWithBlock")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersWithBlockDynQ.Build([]any{arg.Name})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersWithSameNameAndEmail = `-- name: SearchUsersWithSameNameAndEmail :many
SELECT id, name, email, created_at, phone FROM users
WHERE 1 = 1
  AND name = $1 -- :if $1
  AND email = $1 -- :if $1
ORDER BY id ASC
`

var _searchUsersWithSameNameAndEmailDynQ = dynCompile(SearchUsersWithSameNameAndEmail)

type SearchUsersWithSameNameAndEmailParams struct {
	Name *string
}

func (q *SearchQueries) SearchUsersWithSameNameAndEmail(ctx context.Context, db DBTX, arg SearchUsersWithSameNameAndEmailParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsersWithSameNameAndEmail")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersWithSameNameAndEmailDynQ.Build([]any{arg.Name})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersWithTopStyle = `-- name: SearchUsersWithTopStyle :many
SELECT id, name, email, created_at, phone FROM users
WHERE 1 = 1
-- :if $1
  AND ( -- :if $1
    name = $1 -- :if $1
    AND email = $1 -- :if $1
  ) -- :if $1
ORDER BY id ASC
`

var _searchUsersWithTopStyleDynQ = dynCompile(SearchUsersWithTopStyle)

type SearchUsersWithTopStyleParams struct {
	Name *string
}

func (q *SearchQueries) SearchUsersWithTopStyle(ctx context.Context, db DBTX, arg SearchUsersWithTopStyleParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsersWithTopStyle")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersWithTopStyleDynQ.Build([]any{arg.Name})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type SearchQuerier interface {
	SearchUsers(ctx context.Context, db DBTX, arg SearchUsersParams) ([]User, error)
	// Include the combined contact filter only when BOTH email AND phone are provided.
	SearchUsersByContact(ctx context.Context, db DBTX, arg SearchUsersByContactParams) ([]User, error)
	// Filter by a list of IDs. When ids is nil the condition is skipped and all
	// users matching the name are returned (nil slice = inactive filter).
	SearchUsersByIDs(ctx context.Context, db DBTX, arg SearchUsersByIDsParams) ([]User, error)
	SearchUsersOrdered(ctx context.Context, db DBTX, arg SearchUsersOrderedParams) ([]User, error)
	SearchUsersOrderedByID(ctx context.Context, db DBTX, arg SearchUsersOrderedByIDParams) ([]User, error)
	SearchUsersWithBlock(ctx context.Context, db DBTX, arg SearchUsersWithBlockParams) ([]User, error)
	SearchUsersWithSameNameAndEmail(ctx context.Context, db DBTX, arg SearchUsersWithSameNameAndEmailParams) ([]User, error)
	SearchUsersWithTopStyle(ctx context.Context, db DBTX, arg SearchUsersWithTopStyleParams) ([]User, error)
}

var _ SearchQuerier = (*SearchQueries)(nil)
