//go:generate mockgen -source=$GOFILE -destination=mock/$GOFILE -package=mock

// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package dbpostgres

import (
	"context"
	"errors"

	tracing "example"
	"github.com/jackc/pgx/v5"
)

func NewUsersQueries() *UsersQueries {
	return &UsersQueries{}
}

type UsersQueries struct {
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (name, email)
VALUES ($1, $2)
RETURNING id, name, email, created_at, phone
`

type CreateUserParams struct {
	Name  string
	Email string
}

func (q *UsersQueries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (*User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "UsersQueries.CreateUser")
	defer tracer.End()
	row := db.QueryRow(ctx, CreateUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	return &i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

type DeleteUserParams struct {
	ID int64
}

func (q *UsersQueries) DeleteUser(ctx context.Context, db DBTX, arg DeleteUserParams) error {
	ctx, tracer := tracing.StartTracing(ctx, "UsersQueries.DeleteUser")
	defer tracer.End()
	_, err := db.Exec(ctx, DeleteUser, arg.ID)
	return err
}

const GetUser = `-- name: GetUser :one
SELECT id, name, email, created_at, phone FROM users WHERE id = $1 LIMIT 1
`

type GetUserParams struct {
	ID int64
}

func (q *UsersQueries) GetUser(ctx context.Context, db DBTX, arg GetUserParams) (*User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "UsersQueries.GetUser")
	defer tracer.End()
	row := db.QueryRow(ctx, GetUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, name, email, created_at, phone FROM users WHERE name = ANY($1::text[]) ORDER BY name
`

type ListUsersParams struct {
	Names []string
}

func (q *UsersQueries) ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "UsersQueries.ListUsers")
	defer tracer.End()
	rows, err := db.Query(ctx, ListUsers, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1, email = $2
WHERE id = $3
RETURNING id, name, email, created_at, phone
`

type UpdateUserParams struct {
	Name  string
	Email string
	ID    int64
}

func (q *UsersQueries) UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (*User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "UsersQueries.UpdateUser")
	defer tracer.End()
	row := db.QueryRow(ctx, UpdateUser, arg.Name, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	return &i, err
}

type UsersQuerier interface {
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (*User, error)
	DeleteUser(ctx context.Context, db DBTX, arg DeleteUserParams) error
	GetUser(ctx context.Context, db DBTX, arg GetUserParams) (*User, error)
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (*User, error)
}

var _ UsersQuerier = (*UsersQueries)(nil)
