// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filter.sql

package dbsqlite

import (
	"context"
)

const listFilterItems = `-- name: ListFilterItems :many
SELECT id, a, b, c
FROM filter_items
WHERE a = ?1
  AND b = ?2 -- :if $2
  AND c = ?3
ORDER BY id
`

var _listFilterItemsDynQ = dynCompile(listFilterItems)

type ListFilterItemsParams struct {
	A string
	B *string
	C string
}

type ListFilterItemsRow struct {
	ID int64
	A  string
	B  string
	C  string
}

// An optional filter in the middle of the WHERE clause: dropping @b renumbers
// the placeholder for @c.
func (q *Queries) ListFilterItems(ctx context.Context, arg ListFilterItemsParams) ([]ListFilterItemsRow, error) {

	dynQuery, dynArgs := _listFilterItemsDynQ.Build([]any{arg.A, arg.B, arg.C})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilterItemsRow
	for rows.Next() {
		var i ListFilterItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.A,
			&i.B,
			&i.C,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFilterItems = `-- name: SearchFilterItems :many
SELECT id
FROM filter_items
WHERE kind = ?1
  AND id IN (/*SLICE:ids*/?2) -- :if $2
ORDER BY id
`

var _searchFilterItemsDynQ = dynCompile(searchFilterItems)

type SearchFilterItemsParams struct {
	Kind string
	Ids  []int64
}

func (q *Queries) SearchFilterItems(ctx context.Context, arg SearchFilterItemsParams) ([]int64, error) {

	dynQuery, dynArgs := _searchFilterItemsDynQ.Build([]any{arg.Kind, arg.Ids})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
