// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package dbsqlite

import (
	"context"
)

const createOrder = `-- name: CreateOrder :execlastid
INSERT INTO orders (user_id, amount, status)
VALUES (?, ?, ?)
`

type CreateOrderParams struct {
	UserID int64
	Amount float64
	Status string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOrder, arg.UserID, arg.Amount, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, amount, status, created_at FROM orders WHERE id = ? LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserOrderSummary = `-- name: GetUserOrderSummary :one
SELECT u.name, COUNT(o.id) AS order_count, COALESCE(SUM(o.amount), 0) AS total_spent
FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE u.id = ?
GROUP BY u.name
`

type GetUserOrderSummaryRow struct {
	Name       string
	OrderCount int64
	TotalSpent interface{}
}

func (q *Queries) GetUserOrderSummary(ctx context.Context, id int64) (GetUserOrderSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getUserOrderSummary, id)
	var i GetUserOrderSummaryRow
	err := row.Scan(&i.Name, &i.OrderCount, &i.TotalSpent)
	return i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, amount, status, created_at FROM orders WHERE user_id = ? ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE orders SET status = ? WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
