// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package dbsqlite

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price, stock)
VALUES (?, ?, ?)
RETURNING id, name, price, stock, created_at
`

type CreateProductParams struct {
	Name  sql.NullString
	Price float64
	Stock sql.NullInt64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, arg.Price, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, price, stock, created_at FROM products WHERE id = ? LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
	)
	return i, err
}

const getProductPrice = `-- name: GetProductPrice :one
SELECT price FROM products WHERE id = ? LIMIT 1
`

func (q *Queries) GetProductPrice(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, getProductPrice, id)
	var price float64
	err := row.Scan(&price)
	return price, err
}

const getProductsInStock = `-- name: GetProductsInStock :one
SELECT stock FROM products WHERE stock > 0 LIMIT 1
`

func (q *Queries) GetProductsInStock(ctx context.Context) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getProductsInStock)
	var stock sql.NullInt64
	err := row.Scan(&stock)
	return stock, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price, stock, created_at FROM products ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE products SET stock = ? WHERE id = ?
`

type UpdateProductStockParams struct {
	Stock sql.NullInt64
	ID    int64
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.ExecContext(ctx, updateProductStock, arg.Stock, arg.ID)
	return err
}
