// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbsqlite

import (
	"context"
)

const listFilterItems = `-- name: ListFilterItems :many
SELECT id, a, b, c
FROM filter_items
WHERE a = ?1
  AND b = ?2 -- :if $2
  AND c = ?3
ORDER BY id
`

var _listFilterItemsDynQ = dynCompile(listFilterItems)

type ListFilterItemsParams struct {
	A string
	B *string
	C string
}

func (q *Queries) ListFilterItems(ctx context.Context, arg ListFilterItemsParams) ([]FilterItem, error) {

	dynQuery, dynArgs := _listFilterItemsDynQ.Build([]any{arg.A, arg.B, arg.C})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterItem
	for rows.Next() {
		var i FilterItem
		if err := rows.Scan(
			&i.ID,
			&i.A,
			&i.B,
			&i.C,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
