// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbsqlite

import (
	"context"
	"database/sql"
	"time"
)

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = ?1
-- :if $2
  AND email = ?2
  AND phone = ?3 -- :if $3
  AND EXISTS ( -- :if $5
    SELECT 1 FROM orders -- :if $5
    WHERE orders.user_id = users.id -- :if $5
      AND orders.created_at >= ?4 -- :if $4 -- :if $5
  ) -- :if $5
ORDER BY id ASC
`

var _searchUsersDynQ = dynCompile(searchUsers)

type SearchUsersParams struct {
	Name        string
	Email       *string
	Phone       *sql.NullString
	OrdersSince *time.Time
	HasOrders   bool
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {

	dynQuery, dynArgs := _searchUsersDynQ.Build([]any{arg.Name, arg.Email, arg.Phone, arg.OrdersSince, arg.HasOrders})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByContact = `-- name: SearchUsersByContact :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = ?1
  AND (email = ?2 OR phone = ?3) -- :if $2 -- :if $3
ORDER BY id ASC
`

var _searchUsersByContactDynQ = dynCompile(searchUsersByContact)

type SearchUsersByContactParams struct {
	Name  string
	Email *string
	Phone *sql.NullString
}

// Include the combined contact filter only when BOTH email AND phone are provided.
func (q *Queries) SearchUsersByContact(ctx context.Context, arg SearchUsersByContactParams) ([]User, error) {

	dynQuery, dynArgs := _searchUsersByContactDynQ.Build([]any{arg.Name, arg.Email, arg.Phone})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByIDs = `-- name: SearchUsersByIDs :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = ?1
  AND id IN (/*SLICE:ids*/?2) -- :if $2
ORDER BY id ASC
`

var _searchUsersByIDsDynQ = dynCompile(searchUsersByIDs)

type SearchUsersByIDsParams struct {
	Name string
	Ids  []int64
}

// Filter by a list of IDs. When ids is nil the condition is skipped and all
// users matching the name are returned (nil slice = inactive filter).
func (q *Queries) SearchUsersByIDs(ctx context.Context, arg SearchUsersByIDsParams) ([]User, error) {

	dynQuery, dynArgs := _searchUsersByIDsDynQ.Build([]any{arg.Name, arg.Ids})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersOrdered = `-- name: SearchUsersOrdered :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = ?1
  AND email = ?2 -- :if $2
ORDER BY
  created_at DESC, -- :if $3
  name ASC, -- :if $4
  id ASC
`

var _searchUsersOrderedDynQ = dynCompile(searchUsersOrdered)

type SearchUsersOrderedParams struct {
	Name               string
	Email              *string
	OrderCreatedAtDesc bool
	OrderNameAsc       bool
}

func (q *Queries) SearchUsersOrdered(ctx context.Context, arg SearchUsersOrderedParams) ([]User, error) {

	dynQuery, dynArgs := _searchUsersOrderedDynQ.Build([]any{arg.Name, arg.Email, arg.OrderCreatedAtDesc, arg.OrderNameAsc})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersOrderedByID = `-- name: SearchUsersOrderedByID :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = ?1
  AND email = ?2 -- :if $2
ORDER BY
  id ASC, -- :if $3
  id DESC, -- :if $4
  TRUE
`

var _searchUsersOrderedByIDDynQ = dynCompile(searchUsersOrderedByID)

type SearchUsersOrderedByIDParams struct {
	Name   string
	Email  *string
	IdAsc  bool
	IdDesc bool
}

// Every ORDER BY entry is removable. The static `TRUE` keeps the clause valid
// whichever entries drop out, and doubles as the trailing static line sqlc's
// SQLite parser needs: it discards a `-- :if` comment sitting on a statement's
// last line, so an annotation must never be the final token before the `;`.
func (q *Queries) SearchUsersOrderedByID(ctx context.Context, arg SearchUsersOrderedByIDParams) ([]User, error) {

	dynQuery, dynArgs := _searchUsersOrderedByIDDynQ.Build([]any{arg.Name, arg.Email, arg.IdAsc, arg.IdDesc})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersWithBlock = `-- name: SearchUsersWithBlock :many
SELECT id, name, email, created_at, phone FROM users
WHERE 1 = 1
  AND ( -- :if $1
    name = ?1 -- :if $1
    AND email = ?1 -- :if $1
  ) -- :if $1
ORDER BY id ASC
`

var _searchUsersWithBlockDynQ = dynCompile(searchUsersWithBlock)

func (q *Queries) SearchUsersWithBlock(ctx context.Context, name *string) ([]User, error) {

	dynQuery, dynArgs := _searchUsersWithBlockDynQ.Build([]any{name})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersWithPhone = `-- name: SearchUsersWithPhone :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = ?1
  AND phone IS NOT NULL -- :if $2
ORDER BY id ASC
`

var _searchUsersWithPhoneDynQ = dynCompile(searchUsersWithPhone)

type SearchUsersWithPhoneParams struct {
	Name      string
	WithPhone bool
}

// SQLite has no FOR UPDATE, so this stands in for the postgres/mysql lock
// example: a flag-only parameter that gates a clause without binding a value.
func (q *Queries) SearchUsersWithPhone(ctx context.Context, arg SearchUsersWithPhoneParams) ([]User, error) {

	dynQuery, dynArgs := _searchUsersWithPhoneDynQ.Build([]any{arg.Name, arg.WithPhone})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersWithSameNameAndEmail = `-- name: SearchUsersWithSameNameAndEmail :many
SELECT id, name, email, created_at, phone FROM users
WHERE 1 = 1
  AND name = ?1 -- :if $1
  AND email = ?1 -- :if $1
ORDER BY id ASC
`

var _searchUsersWithSameNameAndEmailDynQ = dynCompile(searchUsersWithSameNameAndEmail)

// The same parameter gates (and fills) two conditions.
func (q *Queries) SearchUsersWithSameNameAndEmail(ctx context.Context, name *string) ([]User, error) {

	dynQuery, dynArgs := _searchUsersWithSameNameAndEmailDynQ.Build([]any{name})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersWithTopStyle = `-- name: SearchUsersWithTopStyle :many
SELECT id, name, email, created_at, phone FROM users
WHERE 1 = 1
-- :if $1
  AND ( -- :if $1
    name = ?1 -- :if $1
    AND email = ?1 -- :if $1
  ) -- :if $1
ORDER BY id ASC
`

var _searchUsersWithTopStyleDynQ = dynCompile(searchUsersWithTopStyle)

func (q *Queries) SearchUsersWithTopStyle(ctx context.Context, name *string) ([]User, error) {

	dynQuery, dynArgs := _searchUsersWithTopStyleDynQ.Build([]any{name})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
