// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgtype"
)

type Order struct {
	ID        int64
	UserID    int64
	Amount    pgtype.Numeric
	Status    string
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt time.Time
	Phone     *string
}
