// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	decimal "github.com/shopspring/decimal"
)

type Order struct {
	ID        int64
	UserID    int64
	Amount    decimal.Decimal
	Status    string
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt time.Time
	Phone     *string
}
