// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"errors"

	tracing "example"
	"github.com/jackc/pgx/v4"
	decimal "github.com/shopspring/decimal"
)

func NewOrdersQueries() *OrdersQueries {
	return &OrdersQueries{}
}

type OrdersQueries struct {
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, amount, status)
VALUES ($1, $2, $3)
RETURNING id, user_id, amount, status, created_at
`

type CreateOrderParams struct {
	UserID int64
	Amount decimal.Decimal
	Status string
}

func (q *OrdersQueries) CreateOrder(ctx context.Context, db DBTX, arg CreateOrderParams) (*Order, error) {
	ctx, tracer := tracing.StartTracing(ctx, "OrdersQueries.CreateOrder")
	defer tracer.End()
	row := db.QueryRow(ctx, createOrder, arg.UserID, arg.Amount, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, amount, status, created_at FROM orders WHERE id = $1 LIMIT 1
`

func (q *OrdersQueries) GetOrder(ctx context.Context, db DBTX, id int64) (*Order, error) {
	ctx, tracer := tracing.StartTracing(ctx, "OrdersQueries.GetOrder")
	defer tracer.End()
	row := db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const getUserOrderSummary = `-- name: GetUserOrderSummary :one
SELECT u.name, COUNT(o.id) as order_count, COALESCE(SUM(o.amount), 0) as total_spent
FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE u.id = $1
GROUP BY u.name
`

type GetUserOrderSummaryRow struct {
	Name       string
	OrderCount int64
	TotalSpent interface{}
}

func (q *OrdersQueries) GetUserOrderSummary(ctx context.Context, db DBTX, id int64) (*GetUserOrderSummaryRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "OrdersQueries.GetUserOrderSummary")
	defer tracer.End()
	row := db.QueryRow(ctx, getUserOrderSummary, id)
	var i GetUserOrderSummaryRow
	err := row.Scan(&i.Name, &i.OrderCount, &i.TotalSpent)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, amount, status, created_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *OrdersQueries) ListOrdersByUser(ctx context.Context, db DBTX, userID int64) ([]*Order, error) {
	ctx, tracer := tracing.StartTracing(ctx, "OrdersQueries.ListOrdersByUser")
	defer tracer.End()
	rows, err := db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2 WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64
	Status string
}

func (q *OrdersQueries) UpdateOrderStatus(ctx context.Context, db DBTX, arg UpdateOrderStatusParams) error {
	ctx, tracer := tracing.StartTracing(ctx, "OrdersQueries.UpdateOrderStatus")
	defer tracer.End()
	_, err := db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

type OrdersQuerier interface {
	CreateOrder(ctx context.Context, db DBTX, arg CreateOrderParams) (*Order, error)
	GetOrder(ctx context.Context, db DBTX, id int64) (*Order, error)
	GetUserOrderSummary(ctx context.Context, db DBTX, id int64) (*GetUserOrderSummaryRow, error)
	ListOrdersByUser(ctx context.Context, db DBTX, userID int64) ([]*Order, error)
	UpdateOrderStatus(ctx context.Context, db DBTX, arg UpdateOrderStatusParams) error
}

var _ OrdersQuerier = (*OrdersQueries)(nil)
