// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v4"
)

func NewUsersQueries() *UsersQueries {
	return &UsersQueries{}
}

type UsersQueries struct {
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email)
VALUES ($1, $2)
RETURNING id, name, email, created_at, phone
`

type CreateUserParams struct {
	Name  string
	Email string
}

func (q *UsersQueries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (*User, error) {
	row := db.QueryRow(ctx, createUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

type DeleteUserParams struct {
	ID int64
}

func (q *UsersQueries) DeleteUser(ctx context.Context, db DBTX, arg DeleteUserParams) error {
	_, err := db.Exec(ctx, deleteUser, arg.ID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at, phone FROM users WHERE id = $1 LIMIT 1
`

type GetUserParams struct {
	ID int64
}

func (q *UsersQueries) GetUser(ctx context.Context, db DBTX, arg GetUserParams) (*User, error) {
	row := db.QueryRow(ctx, getUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, created_at, phone FROM users WHERE name = ANY($1::text[]) ORDER BY name
`

type ListUsersParams struct {
	Names []string
}

func (q *UsersQueries) ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]*User, error) {
	rows, err := db.Query(ctx, listUsers, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1, email = $2
WHERE id = $3
RETURNING id, name, email, created_at, phone
`

type UpdateUserParams struct {
	Name  string
	Email string
	ID    int64
}

func (q *UsersQueries) UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (*User, error) {
	row := db.QueryRow(ctx, updateUser, arg.Name, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	return &i, err
}

type UsersQuerier interface {
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (*User, error)
	DeleteUser(ctx context.Context, db DBTX, arg DeleteUserParams) error
	GetUser(ctx context.Context, db DBTX, arg GetUserParams) (*User, error)
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]*User, error)
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (*User, error)
}

var _ UsersQuerier = (*UsersQueries)(nil)
